import type { WonderCard } from './types.js';

export const WONDER_CARDS = [
  {
    id: 'the-appian-way',
    name: 'The Appian Way',
    cost: { stone: 2, clay: 2, papyrus: 1 },
    effect: { kind: 'coinsNow', amount: 3, opponentLose: 3 },
    vp: 3,
    extraTurn: true,
  },
  {
    id: 'circus-maximus',
    name: 'Circus Maximus',
    cost: { stone: 2, wood: 1, glass: 1 },
    effect: { kind: 'discardOpponentCard', color: 'grey' },
    vp: 3,
    shields: 1,
  },
  {
    id: 'the-colossus',
    name: 'The Colossus',
    cost: { clay: 3, glass: 1 },
    vp: 3,
    shields: 2,
  },
  {
    id: 'the-great-library',
    name: 'The Great Library',
    cost: { wood: 3, papyrus: 1, glass: 1 },
    effect: { kind: 'chooseProgressFromDiscarded', draw: 3, keep: 1 },
    vp: 4,
  },
  {
    id: 'the-great-lighthouse',
    name: 'The Great Lighthouse',
    cost: { wood: 1, stone: 1, papyrus: 2 },
    effect: { kind: 'production', oneOf: ['wood', 'stone', 'clay'] },
    vp: 4,
  },
  {
    id: 'the-hanging-gardens',
    name: 'The Hanging Gardens',
    cost: { wood: 2, papyrus: 1, glass: 1 },
    effect: { kind: 'coinsNow', amount: 6 },
    vp: 3,
    extraTurn: true,
  },
  {
    id: 'the-mausoleum',
    name: 'The Mausoleum',
    cost: { clay: 2, glass: 2, papyrus: 1 },
    effect: { kind: 'constructFromDiscard' },
    vp: 2,
  },
  {
    id: 'piraeus',
    name: 'Piraeus',
    cost: { wood: 2, stone: 1, clay: 1 },
    effect: { kind: 'production', oneOf: ['glass', 'papyrus'] },
    vp: 2,
    extraTurn: true,
  },
  {
    id: 'the-pyramids',
    name: 'The Pyramids',
    cost: { stone: 3, papyrus: 1 },
    vp: 9,
  },
  {
    id: 'the-sphinx',
    name: 'The Sphinx',
    cost: { stone: 1, clay: 1, glass: 2 },
    vp: 6,
    extraTurn: true,
  },
  {
    id: 'the-statue-of-zeus',
    name: 'The Statue of Zeus',
    cost: { wood: 1, stone: 1, clay: 1, papyrus: 2 },
    effect: { kind: 'discardOpponentCard', color: 'brown' },
    vp: 3,
    shields: 1,
  },
  {
    id: 'the-temple-of-artemis',
    name: 'The Temple of Artemis',
    cost: { wood: 1, stone: 1, glass: 1, papyrus: 1 },
    effect: { kind: 'coinsNow', amount: 12 },
    vp: 0,
    extraTurn: true,
  },
] satisfies readonly WonderCard[];
